
var code = 100;
var UNKNOWN_ERROR                   = {message: 'UNKNOWN_ERROR', code: code++};
var IDENTIFIER_IS_INCORRECT         = {message: 'IDENTIFIER_IS_INCORRECT', code: code++};
var IDENTIFIER_IS_UNAVAILABLE       = {message: 'IDENTIFIER_IS_UNAVAILABLE', code: code++};
var IDENTIFIER_NOT_OWNED            = {message: 'IDENTIFIER_NOT_OWNED', code: code++};
var IDENTIFIER_RESERVATION_FAILED   = {message: 'IDENTIFIER_RESERVATION_FAILED', code: code++};
var IDENTIFIER_NO_ADDRESS           = {message: 'IDENTIFIER_NO_ADDRESS', code: code++};
var CONTRACT_DOESNT_EXIST           = {message: 'CONTRACT_DOESNT_EXIST', code: code++};
var CONTRACT_COMPILATION_ERROR      = {message: 'CONTRACT_COMPILATION_ERROR', code: code++};
var CONTRACT_DEPLOYMENT_ERROR       = {message: 'CONTRACT_DEPLOYMENT_ERROR', code: code++};
var CONTRACT_REGISTRATION_FAILED    = {message: 'CONTRACT_REGISTRATION_FAILED', code: code++};
var FROM_IS_INCORRECT               = {message: 'FROM_IS_INCORRECT', code: code++};
var TO_IS_INCORRECT                 = {message: 'TO_IS_INCORRECT', code: code++};
var TO_IDENTIFIER_NO_ADDRESS         = {message: 'TO_IDENTIFIER_NO_ADDRESS', code: code++};

module.exports = {
    UNKNOWN_ERROR: UNKNOWN_ERROR,
    IDENTIFIER_IS_INCORRECT: IDENTIFIER_IS_INCORRECT,
    IDENTIFIER_IS_UNAVAILABLE: IDENTIFIER_IS_UNAVAILABLE,
    IDENTIFIER_NOT_OWNED: IDENTIFIER_NOT_OWNED,
    IDENTIFIER_RESERVATION_FAILED: IDENTIFIER_RESERVATION_FAILED,
    IDENTIFIER_NO_ADDRESS: IDENTIFIER_NO_ADDRESS,
    CONTRACT_DOESNT_EXIST: CONTRACT_DOESNT_EXIST,
    CONTRACT_COMPILATION_ERROR: CONTRACT_COMPILATION_ERROR,
    CONTRACT_DEPLOYMENT_ERROR: CONTRACT_DEPLOYMENT_ERROR,
    CONTRACT_REGISTRATION_FAILED: CONTRACT_REGISTRATION_FAILED,
    FROM_IS_INCORRECT: FROM_IS_INCORRECT,
    TO_IS_INCORRECT: TO_IS_INCORRECT,
    TO_IDENTIFIER_NO_ADDRESS: TO_IDENTIFIER_NO_ADDRESS
};

